__author__ = 'linfengji'

MSG_TYPE_TEXT = 'text'
MSG_TYPE_IMAGE = 'image'
MSG_TYPE_VIDEO = 'video'
MSG_TYPE_SHORTVIDEO = 'shortvideo'
MSG_TYPE_LOCATION = 'location'
MSG_TYPE_LINK = 'link'

MSG_TYPES = [MSG_TYPE_TEXT, MSG_TYPE_IMAGE, MSG_TYPE_VIDEO, MSG_TYPE_LOCATION, MSG_TYPE_LOCATION, MSG_TYPE_LINK]